/lidar_points/top:
  need_calibration: false
  use_points: false
  is_main: true
  load_from_file: true
  file_path: /home/wind/calib_data_1206/ground/lidar_points_top/0.pcd
  transform:
    translation:
      - 1.559
      - -0.018
      - 1.764
    rotation:
      - 1
      - 0
      - -0.001
      - -0.002
    rotation_euler:
      - 0
      - -0.002
      - -0.004
/lidar_points/front:
  need_calibration: true
  use_points: false
  is_main: false
  load_from_file: true
  file_path: /home/wind/calib_data_1206/ground/lidar_points_front/0.pcd
  transform:
    translation:
      - 1.755
      - -0.645
      - 1.375
    rotation:
      - -0.006
      - 0.919
      - -0.394
      - -0.006
    rotation_euler:
      - -3.135
      - 0.016
      - -0.8100000000000001
/lidar_points/back:
  need_calibration: true
  use_points: false
  is_main: false
  load_from_file: true
  file_path: /home/wind/calib_data_1206/ground/lidar_points_back/0.pcd
  transform:
    translation:
      - -0.55
      - 0.65
      - 1.3
    rotation:
      - 0.007
      - 0.413
      - 0.91
      - -0.001
    rotation_euler:
      - 3.138
      - 0.014
      - 2.289
