/lidar_points/top:
  need_calibration: true
  use_points: true
  is_main: true
  load_from_file: true
  file_path: /home/wind/Downloads/capture/0125/lidar_points_top/0.pcd
  transform:
    translation:
      - 1.541
      - -0.018
      - 1.707
    rotation:
      - 1
      - 0
      - -0.006
      - -0.002
    rotation_euler:
      - 0
      - -0.013
      - -0.004
/lidar_points/front:
  need_calibration: true
  use_points: false
  is_main: false
  load_from_file: true
  file_path: /home/wind/Downloads/capture/0125/lidar_points_front/0.pcd
  transform:
    translation:
      - 1.76
      - -0.633
      - 1.375
    rotation:
      - 0
      - 0
      - 0
      - 0
    rotation_euler:
      - -3.131
      - 0
      - -0.771
/lidar_points/back:
  need_calibration: true
  use_points: false
  is_main: false
  load_from_file: true
  file_path: /home/wind/Downloads/capture/0125/lidar_points_back/0.pcd
  transform:
    translation:
      - -0.55
      - 0.6
      - 1.293
    rotation:
      - 0
      - 0
      - 0
      - 0
    rotation_euler:
      - 3.11
      - 0.013
      - 2.351
