/lidar_points/top:
  need_calibration: true
  use_points: true
  is_main: true
  load_from_file: true
  file_path: /home/wind/Downloads/capture/build3/ground/lidar_points_top/0.pcd
  transform:
    translation:
      - 0.286
      - 0
      - 1.31
    rotation:
      - 0
      - 0
      - 0
      - 0
    rotation_euler:
      - -0.005
      - 0.002
      - 0.01
/lidar_points/front:
  need_calibration: true
  use_points: false
  is_main: false
  load_from_file: true
  file_path: /home/wind/Downloads/capture/build3/ground/lidar_points_front/0.pcd
  transform:
    translation:
      - 0.29
      - 0.02
      - 1.455
    rotation:
      - 0
      - 0
      - 0
      - 0
    rotation_euler:
      - -0.029
      - 0.061
      - -0.17
/lidar_points/left:
  need_calibration: true
  use_points: false
  is_main: false
  load_from_file: true
  file_path: /home/wind/Downloads/capture/build3/ground/lidar_points_left/0.pcd
  transform:
    translation:
      - 0.27
      - -0.009
      - 1.378
    rotation:
      - 0
      - 0
      - 0
      - 0
    rotation_euler:
      - 0.093
      - 0.023
      - -0.16
/lidar_points/right:
  need_calibration: true
  use_points: false
  is_main: false
  load_from_file: true
  file_path: /home/wind/Downloads/capture/build3/ground/lidar_points_right/0.pcd
  transform:
    translation:
      - 0.2
      - -0.05
      - 1.378
    rotation:
      - 0
      - 0
      - 0
      - 0
    rotation_euler:
      - -0.098
      - -0.003
      - -0.14
